name: Daily Grocery Scraper

on:
  schedule:
    - cron: '0 16 * * *' # Runs at 16:00 UTC (12:00 PM EST) every day
  workflow_dispatch: # Allows you to click a button to run it manually

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Google Chrome 
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the scraper
        env:
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          WEEE_COOKIE: ${{ secrets.WEEE_COOKIE }}
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAILS: ${{ secrets.RECEIVER_EMAILS }}
          TWILIO_SENDER: ${{ secrets.TWILIO_SENDER }}
          WHATSAPP_RECEIVERS: ${{ secrets.WHATSAPP_RECEIVERS }}
          OWNER_EMAIL: ${{ secrets.OWNER_EMAIL }}
        run: python scraper.py
